#list of paletttes available in grafify package
graf_palettes <- list(
  `okabe_ito` = get_graf_colours("ok_orange",
                                 "ok_skyblue",
                                 "ok_bluegreen",
                                 "ok_yellow",
                                 "ok_blue",
                                 "ok_vermillion",
                                 "ok_redpurple",
                                 "ok_grey"),
  `bright` = get_graf_colours( "bright_blue",
                               "bright_cyan",
                               "bright_green",
                               "bright_yellow",
                               "bright_red",
                               "bright_purple",
                               "bright_grey"),
  `pale` = get_graf_colours( "pale_blue",
                             "pale_cyan",
                             "pale_green",
                             "pale_yellow",
                             "pale_red",
                             "pale_grey"),
  `muted` = get_graf_colours("muted_indigo",
                             "muted_cyan",
                             "muted_teal",
                             "muted_green",
                             "muted_oliver",
                             "muted_sand",
                             "muted_rose",
                             "muted_wine",
                             "muted_purple",
                             "pale_grey"),
  `light` = get_graf_colours(  "light_blue",
                               "light_cyan",
                               "light_mint",
                               "light_pear",
                               "light_olive",
                               "light_yellow",
                               "light_orange",
                               "light_pink",
                               "pale_grey"),
  `dark` = get_graf_colours(  "dark_blue",
                              "dark_cyan",
                              "dark_green",
                              "dark_yellow",
                              "dark_red",
                              "dark_grey"),
  `all_grafify` = get_graf_colours(  "ok_orange",
                                  "ok_skyblue",
                                  "ok_bluegreen",
                                  "ok_yellow",
                                  "ok_blue",
                                  "ok_vermillion",
                                  "ok_redpurple",
                                  "ok_grey",
                                  "bright_blue",
                                  "bright_cyan",
                                  "bright_green",
                                  "bright_yellow",
                                  "bright_red",
                                  "bright_purple",
                                  "bright_grey",
                                  "muted_indigo",
                                  "muted_cyan",
                                  "muted_teal",
                                  "muted_green",
                                  "muted_oliver",
                                  "muted_sand",
                                  "muted_rose",
                                  "muted_wine",
                                  "muted_purple",
                                  "pale_grey",
                                  "pale_blue",
                                  "pale_cyan",
                                  "pale_green",
                                  "pale_yellow",
                                  "pale_red",
                                  "pale_grey",
                                  "dark_blue",
                                  "dark_cyan",
                                  "dark_green",
                                  "dark_yellow",
                                  "dark_red",
                                  "dark_grey",
                                  "light_blue",
                                  "light_cyan",
                                  "light_mint",
                                  "light_pear",
                                  "light_olive",
                                  "light_yellow",
                                  "light_orange",
                                  "light_pink",
                                  "pale_grey"))
